
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-appgate
  name: appgate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-appgate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-appgate
    spec:
      containers:
        - image: docker.io/jaamarti/appgate:v1
          name: appgate
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
