apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-08-26T00:59:49Z"
  labels:
    app.kubernetes.io/name: load-balancer-appgate
  name: appgate-service
  namespace: default
  resourceVersion: "63013"
  uid: ed63b818-3340-423b-a650-e577b6522e10
spec:
  clusterIP: 10.105.210.183
  clusterIPs:
  - 10.105.210.183
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30790
    port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: load-balancer-appgate
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1
