apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster
  region: us-east-2

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  subnets:
    private:
      us-west-2b:
        id: <subnet-id>
      us-west-2c:
        id: <subnet-id>
      us-west-2d:
        id: <subnet-id>

nodeGroups:
- name: ng1
  instanceType: m5.large
  desiredCapacity: 2
  privateNetworking: true